# "variables":{"owner":"TestOrg","repo":"20250930-bt626-repository","per_page":100}
query ($owner: String!, $repo: String!, $per_page: Int!, $cursor: String) {
    repository(owner: $owner, name: $repo){
        deployments(first: $per_page, after: $cursor, orderBy: { direction: DESC, field: CREATED_AT }) {
            edges {
                cursor
                node {
                    createdAt
                    repository {
                        id: databaseId
                        url
                        node_id: id
                        name
                        owner {
                            login
                        }
                    }
                    databaseId
                    commitOid
                    task
                    ref {
                        name
                        id
                    }
                    environment
                    description
                    statuses(last: 5) {
                        nodes {
                            createdAt
                            updatedAt
                            state
                            logUrl
                        }
                    }
                    latestStatus {
                        environmentUrl
                        logUrl
                        state
                        id
                        createdAt
                        updatedAt
                    }
                }
            }
        }
    }
    rateLimit {
        cost
    }
}
